# fly.toml app configuration file generated for weexchat on 2023-08-24T20:32:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weexchat"
primary_region = "sjc"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "weexchat.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
