name: Release

on:
  workflow_run:
    workflows: ["Integration"]
  push:
    branches: ["master"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-website:
    name: Continuous Deployment
    if: github.repository_owner == 'phaleth'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --no-cache -c fly.toml
